### ISSUE TITLE
Latest DockerHub version - 0.6.2 (Possibly Unstable)

### ISSUE THREAD

**Issue by abjoseph** [Division42LLC/division42llc-dotnet-webca#3]
Following the setup instructions on the dockerHub page for webCA I the following status at the docker CLI interface whenever I create an instance of the latest image (0.6.2)

CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                            PORTS                                      NAMES
08d4f165b06a        division42llc/dotnet-webca:latest   "/bin/bash /usr/lo..."   5 minutes ago       Restarting (131) 19 seconds ago                                              webCA-Cyrotek

Even after trying docker stop command it remains stuck in the above status.

I've reverted to the previous image version (0.6.1) until the next release. 

Thanks for your time and this very useful utility.

P.S The exposed port seems to still be 80 and not 8080. Additionally, if there is any way I can assist/contribute please let me know.

**Comment by RobSeder** [comment]
@abjoseph Yes, please - clone the code, fix/update what you'd like and then do a Pull Request. I have limited time to work on this, and this was just a thrown-together solution for my home lab.

**Comment by RobSeder** [comment]
@abjoseph I've put out a few small fixes, with `0.6.5` (or `:latest` in the Docker Store) being the latest. I believe this is resolved. If you have any other issues, please re-open an issue. thanks.
