### ISSUE TITLE
Signing certificate

### ISSUE THREAD

**Issue by ybizeul** [Division42LLC/division42llc-dotnet-webca#7]
It seems one thing is missing from webCA is the possibility to sign CSRs.

Many products generate their own keys and then deliver a Certificate Signing Request for you to sign and return.

**Comment by RobSeder** [comment]
@ybizeul I won't have time in the foreseeable future to work on this. Feel free to ``fork`` the repository and then do a Pull Request of the change that you want to see. Sorry I can't be more help!
